"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, ShieldCheck, QrCode, Loader2, CheckCircle2 } from "lucide-react";

interface TwoFactorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onEnable: () => void;
}

export function TwoFactorModal({ isOpen, onClose, onEnable }: TwoFactorModalProps) {
  const [step, setStep] = useState(1);
  const [code, setCode] = useState("");
  const [verifying, setVerifying] = useState(false);

  if (!isOpen) return null;

  const handleVerify = async () => {
    setVerifying(true);
    await new Promise(res => setTimeout(res, 1000));
    setVerifying(false);
    setStep(3); // Success step
    setTimeout(() => {
      onEnable();
      onClose();
      // Reset for next time just in case
      setTimeout(() => { setStep(1); setCode(""); }, 500);
    }, 1500);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="absolute inset-0 bg-black/60 backdrop-blur-sm"
          onClick={step === 3 || verifying ? undefined : onClose}
        />
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="relative w-full max-w-md bg-[#0f1117] rounded-2xl shadow-2xl border border-slate-800 overflow-hidden"
        >
          <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/50">
            <div className="flex items-center gap-2 text-white font-bold">
              <ShieldCheck className="w-5 h-5 text-brand-400" />
              Enable Two-Factor Authentication
            </div>
            {step !== 3 && !verifying && (
              <button onClick={onClose} className="p-1.5 rounded-lg text-slate-400 hover:bg-slate-800 hover:text-white transition-colors">
                <X className="w-5 h-5" />
              </button>
            )}
          </div>

          <div className="p-6">
            {step === 1 && (
              <div className="space-y-6 text-center">
                <p className="text-sm text-slate-400">
                  Scan this QR code with your authenticator app (e.g., Google Authenticator, Authy).
                </p>
                <div className="w-48 h-48 mx-auto bg-white rounded-xl p-2 flex items-center justify-center">
                  <img 
                    src={`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent("otpauth://totp/MomPlan:admin@momplan.com?secret=ABCDEFGHIJKLMNOP&issuer=MomPlan")}`}
                    alt="2FA QR Code"
                    className="w-full h-full object-contain"
                  />
                </div>
                <div className="space-y-1.5 text-left">
                  <label className="text-xs font-semibold text-slate-300">Or enter this code manually:</label>
                  <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 font-mono text-center text-brand-400 tracking-widest">
                    ABCD EFGH IJKL MNOP
                  </div>
                </div>
                <button onClick={() => setStep(2)} className="btn-primary w-full justify-center py-2.5">
                  I have scanned the code
                </button>
              </div>
            )}

            {step === 2 && (
              <div className="space-y-6">
                <p className="text-sm text-slate-400 text-center">
                  Enter the 6-digit verification code generated by your authenticator app.
                </p>
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-300 uppercase tracking-wider">Verification Code</label>
                  <input
                    type="text"
                    placeholder="000 000"
                    value={code}
                    onChange={(e) => setCode(e.target.value.replace(/\D/g, '').substring(0, 6))}
                    className="input w-full text-center text-xl tracking-[0.5em] font-mono"
                    autoFocus
                  />
                </div>
                <div className="flex gap-3">
                  <button onClick={() => setStep(1)} disabled={verifying} className="btn-secondary flex-1 justify-center">
                    Back
                  </button>
                  <button 
                    onClick={handleVerify} 
                    disabled={code.length < 6 || verifying} 
                    className="btn-primary flex-1 justify-center gap-2"
                  >
                    {verifying ? <Loader2 className="w-4 h-4 animate-spin" /> : <ShieldCheck className="w-4 h-4" />}
                    Verify
                  </button>
                </div>
              </div>
            )}

            {step === 3 && (
              <div className="py-8 text-center space-y-4">
                <div className="w-16 h-16 rounded-full bg-emerald-500/15 text-emerald-400 flex items-center justify-center mx-auto mb-2">
                  <CheckCircle2 className="w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold text-white">2FA Enabled!</h3>
                <p className="text-sm text-slate-400">
                  Your admin account is now protected with two-factor authentication.
                </p>
              </div>
            )}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
